# Use an official Node.js runtime as a parent image
FROM node:21

# Create and define the node_modules's cache directory.
WORKDIR /cache

# Install app dependencies
COPY package*.json ./
RUN npm install

# Create and define the app working directory
WORKDIR /app
ENV NODE_OPTIONS=--openssl-legacy-provider
ENV PATH=/app/node_modules/.bin:$PATH
COPY . .

# Expose the application port
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]
