version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: sign_ui
    restart: unless-stopped
    ports:
      - "3001:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    command: bash
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    container_name: sign_backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ./backend:/app/
    environment:
      - DATABASE_URL=postgresql://admin:test@database:5432/sign_db
      - FRONTEND_URL=http://localhost:3000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  database:
    image: postgres:latest
    container_name: sign_db
    ports:
      - "5432:5432"
    volumes:
      - sign_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sign_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=test

volumes:
  sign_db_data:
