version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: sign_ui
    restart: unless-stopped
    ports:
      - "3001:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/ && npm start"

  test:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    command: ["npm", "test"]

  backend:
    build: ./backend
    container_name: sign_backend
    ports:
      - "8001:8001"
    depends_on:
      - database
    volumes:
      - ./backend:/app/

  database:
    build: ./database
    container_name: sign_db
    ports:
      - "5432:5432"
    volumes:
      - sign_db_data:/var/lib/postgresql/data

volumes:
  sign_db_data:
