version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: sign_ui
    restart: unless-stopped
    ports:
      - "3001:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/ && npm run dev"

  test:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    command: [ "npm", "test" ]

  backend:
    build: ./backend
    container_name: sign_backend
    ports:
      - "8001:8000"
    depends_on:
      - database
    volumes:
      - ./backend:/app/

  database:
    image: postgres:latest
    container_name: sign_db
    environment:
      POSTGRES_DB: sign_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - sign_db_data:/var/lib/postgresql/data

volumes:
  sign_db_data:
